version: 2.1

orbs:
  slack: circleci/slack@4.3.0
  sonarcloud: sonarsource/sonarcloud@1.0.3

commands:
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1


slack-fail-post-step: &slack-fail-post-step
  post-steps:
      - notify_slack_error

slack-fail-success-post-step: &slack-fail-success-post-step
  post-steps:
      - notify_slack_error
      - notify_slack_pass

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:16.15.1-browsers

jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - '*'
  test_and_coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run tests
          command: npm test
      - persist_to_workspace:
          root: .
          paths:
            - '*'

  codequality:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - sonarcloud/scan

  storybook:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build Storybook
          command: npm run build-storybook
      - run:
          name: Publish Storybook
          command: npx chromatic --exit-zero-on-changes --project-token=$storybook_TOKEN --ci

  npmjs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build Project
          command: npm run build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish Project
          command: npm publish --access public

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - install_dependencies
      - test_and_coverage:
          requires:
              - install_dependencies
          filters:
                branches:
                  ignore: main
          <<: *slack-fail-post-step
      - codequality:
          requires:
              - test_and_coverage
          filters:
                branches:
                  ignore: main
          <<: *slack-fail-post-step
      - storybook:
          requires:
              - codequality
          filters:
                branches:
                  only:
                    - main
          <<: *slack-fail-post-step
      - npmjs:
          requires:
              - storybook
          filters:
             branches:
               only:
                 - main
          <<: *slack-fail-success-post-step